### ISSUE TITLE
Issues with KeyError: 'end'

### ISSUE THREAD

**Issue by cying111** [rambaut/readucks#2]
Hi, I am trying Readucks now, but seem to run into the error below, not sure what is going on
0 / 1 (0.0%)Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/readucks", line 11, in <module>
    load_entry_point('readucks==0.0.1', 'console_scripts', 'readucks')()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/readucks/readucks.py", line 80, in main
    process_files(args.input_path, output, barcode_set, args.limit_barcodes_to, settings, args.verbosity, args.threads)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/readucks/readucks.py", line 136, in process_files
    process_read_file(read_file, output, barcodes, settings, barcode_counts, verbosity, threads)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/readucks/readucks.py", line 245, in process_read_file
    results = pool.map(demux_func, reads)
  File "/home/ubuntu/miniconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ubuntu/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/ubuntu/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/miniconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/readucks/demuxer.py", line 52, in demux_read
    result_end = get_score(barcode_id, query_end, barcodes[barcode_id]['end'], gap_open, gap_extend, nuc_matrix)
KeyError: 'end'

**Comment by rmcolq** [comment]
It looks like the field 'end' is not known for the barcode set you have chosen. What was the command you tried to run?

**Comment by rmcolq** [comment]
Assuming the issue was with `--rapid_barcodes`, I have pushed some changes to the master branch. If you pull the tip of master, it should hopefully now work for you.

**Comment by cying111** [comment]
yes, i am using the --rapid_barcodes setting and this is the code I'm using:
readucks -i test/sub_sample.fastq -o demuxed_readucks/ -b  -t 3  --rapid_barcodes. It seems working now~ Thanks!

**Comment by rmcolq** [comment]
Excellent!
